name: Deploy to VPS

# Триггер: запускать при пуше в ветку main
on:
  push:
    branches:
      - main # Или master, в зависимости от вашей основной ветки

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest # Запускать на последней версии Ubuntu от GitHub

    steps:
      # Шаг 1: Установка SSH-ключа из секретов
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'

      # Шаг 2: Добавляем IP сервера в known_hosts, чтобы избежать вопроса о доверии
      - name: Add to known hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # Шаг 3: Подключаемся к VPS и запускаем наш скрипт деплоя
      - name: Deploy to Server
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd ~ && ./${{ secrets.DEPLOY_SCRIPT }}"
